In [1]:
import tensorflow as tf
from tensorflow.python.lib.io import file_io
from tqdm import tqdm
import numpy as np

2023-11-16 12:15:27.257436: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-16 12:15:32.116293: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /global/software/sl-7.x86_64/modules/langs/cuda/11.2/lib64:/global/home/groups/consultsw/sl-7.x86_64/modules/cudnn/7.0.5-cuda9.0/lib64:/global/software/sl-7.x86_64/modules/langs/python/3.7/lib
2023-11-16 12:15:32.116495: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open s

In [23]:
class Parser:
    def __init__(self, seq_length=524288, target_length=896, num_targets=5313, seq_1hot=True, seq_depth=4, seq_length_crop=None):
        self.seq_length = seq_length
        self.target_length = target_length
        self.num_targets = num_targets
        self.seq_1hot = seq_1hot
        self.seq_depth = seq_depth
        self.seq_length_crop = seq_length_crop

    def parse_proto(self, example_protos, raw=False):
        """Parse TFRecord protobuf."""

        # define features
        features = {
            TFR_INPUT: tf.io.FixedLenFeature([], tf.string),
            TFR_OUTPUT: tf.io.FixedLenFeature([], tf.string)
        }

        # parse example into features
        parsed_features = tf.io.parse_single_example(example_protos, features=features)

        # decode sequence
        sequence = tf.io.decode_raw(parsed_features[TFR_INPUT], tf.uint8)
#         if not raw:
#             if self.seq_1hot:
#                 sequence = tf.reshape(sequence, [self.seq_length])
#                 sequence = tf.one_hot(sequence, 1+self.seq_depth, dtype=tf.uint8)
#                 sequence = sequence[:,:-1]  # drop N
#             else:
#                 sequence = tf.reshape(sequence, [self.seq_length, self.seq_depth])
#             if self.seq_length_crop is not None:
#                 crop_len = (self.seq_length - self.seq_length_crop) // 2
#                 sequence = sequence[crop_len:-crop_len,:]
#             sequence = tf.cast(sequence, tf.uint8)

        # decode targets
        targets = tf.io.decode_raw(parsed_features[TFR_OUTPUT], tf.float16)
        if not raw:
            targets = tf.reshape(targets, [self.target_length, self.num_targets])
            targets = tf.cast(targets, tf.float32)

        return sequence, targets

In [24]:
TFR_INPUT = 'sequence'  # This needs to be the actual name used in your TFRecords for the sequence
TFR_OUTPUT = 'target'  # This needs to be the actual name used in your TFRecords for the targets

tfrs_path = '/clusterfs/nilah/richard/basenji2/data_pretrained_basenji2/human/tfrecords/'
tfr_filename = 'train-0-1.tfr'
tfr_output_filename = '/global/scratch/users/dixonluinenburg/cs282a_preprocessing/tfr_testing/recreate_train-0-1.tfr'
parser = Parser()
dataset = tf.data.TFRecordDataset(tfrs_path+tfr_filename,compression_type='ZLIB')
parsed_dataset = dataset.map(parser.parse_proto)    

In [40]:
def _bytes_feature(value):
    """Returns a bytes_list from a string / byte."""
    if isinstance(value, type(tf.constant(0))):
        value = value.numpy() # BytesList won't unpack a string from an EagerTensor.
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))
def feature_bytes(values):
    """Convert numpy arrays to bytes features."""
    values = values.flatten().tobytes()
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[values]))
def serialize_example(sequence, target):
    target = np.array(target).astype('float16')
    serialized_sequence = sequence.numpy().tobytes()
    
    features_dict = {
        TFR_INPUT: tf.train.Feature(bytes_list=tf.train.BytesList(value=[serialized_sequence])),
        TFR_OUTPUT: feature_bytes(target)
    }
    example = tf.train.Example(features=tf.train.Features(feature=features_dict))
    return example

In [37]:
with tf.io.TFRecordWriter(tfr_output_filename,options=options) as writer:
    for sequence,targets in tqdm(parsed_dataset,total=256):
        print(sequence,targets)

  1%|          | 3/256 [00:00<00:21, 11.79it/s]

tf.Tensor([0 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.07519531 0.01112366 0.01609802 ... 0.         0.         0.        ]
 [0.0881958  0.01392365 0.03829956 ... 0.         0.         0.        ]
 [0.05108643 0.01622009 0.01737976 ... 0.         0.         0.        ]
 ...
 [0.00142574 0.001544   0.         ... 0.         0.         0.        ]
 [0.00675964 0.         0.         ... 0.         0.         0.        ]
 [0.05609131 0.0559082  0.06762695 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.06958008 0.06192017 0.         ... 0.14208984 0.         0.        ]
 [0.06665039 0.0425415  0.03186035 ... 0.         0.         0.19018555]
 [0.04772949 0.01244354 0.01963806 ... 0.         0.         0.        ]
 ...
 [0.09320068 0.06671143 0.         ... 0.         0.         0.        ]
 [0.09973145 0.03692627 0.01110077 ... 0.         0.         0.        ]
 [0.0589294

  3%|▎         | 7/256 [00:00<00:16, 14.95it/s]

tf.Tensor([0 0 1 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.08758545 0.1607666  0.10845947 ... 0.         0.         0.        ]
 [0.07965088 0.0758667  0.04248047 ... 0.         0.         0.        ]
 [0.06768799 0.05587769 0.05859375 ... 0.         0.         0.        ]
 ...
 [0.1071167  0.1348877  0.28125    ... 0.17297363 0.         0.        ]
 [0.08081055 0.0949707  0.18603516 ... 0.         0.         0.        ]
 [0.11560059 0.15039062 0.2631836  ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 1 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.0574646  0.06378174 0.01029968 ... 0.         0.         0.        ]
 [0.0047226  0.0048027  0.         ... 0.         0.         0.        ]
 [0.03335571 0.03765869 0.02542114 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00190163 0.00617599 0.         ... 0.         0.         0.        ]
 [0.0082855

  4%|▍         | 11/256 [00:00<00:15, 15.79it/s]

tf.Tensor([0 0 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.06628418 0.02578735 0.01577759 ... 0.         0.         0.        ]
 [0.06365967 0.02326965 0.00997925 ... 0.         0.22692871 0.        ]
 [0.0446167  0.01660156 0.         ... 0.         0.         0.        ]
 ...
 [0.14038086 0.12817383 0.16833496 ... 0.0484314  0.3630371  0.13830566]
 [0.14611816 0.1229248  0.26513672 ... 0.         0.         0.        ]
 [0.07183838 0.10620117 0.33422852 ... 0.         0.05123901 0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([1 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.04174805 0.09460449 0.01078033 ... 0.         0.         0.        ]
 [0.03695679 0.01745605 0.         ... 0.07928467 0.         0.        ]
 [0.04675293 0.02781677 0.         ... 0.         0.         0.        ]
 ...
 [0.03897095 0.10272217 0.04650879 ... 0.         0.         2.3945312 ]
 [0.0345459  0.03814697 0.         ... 0.         0.         0.        ]
 [0.0434265

  6%|▌         | 15/256 [00:00<00:14, 16.83it/s]

tf.Tensor([1 0 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.05813599 0.1116333  0.17333984 ... 0.         0.         0.        ]
 [0.01287079 0.0174408  0.00209236 ... 0.         0.         0.        ]
 [0.00137806 0.0026207  0.00466537 ... 0.         0.         0.        ]
 ...
 [0.02545166 0.05108643 0.05407715 ... 0.         0.         0.        ]
 [0.00894928 0.01315308 0.         ... 0.         0.         0.        ]
 [0.02297974 0.02984619 0.         ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.18054199 0.08532715 0.19506836 ... 0.         0.02464294 0.        ]
 [0.18054199 0.07080078 0.23205566 ... 0.20910645 0.30786133 0.5341797 ]
 [0.21813965 0.09387207 0.3251953  ... 0.         0.         0.        ]
 ...
 [0.8413086  0.72216797 0.41503906 ... 0.         0.03955078 0.97509766]
 [0.85058594 0.38745117 0.3869629  ... 0.         0.05856323 0.        ]
 [1.8291016

  7%|▋         | 19/256 [00:01<00:13, 17.08it/s]

tf.Tensor([0 1 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.06445312 0.034729   0.02059937 ... 0.         0.         0.        ]
 [0.11181641 0.06604004 0.03121948 ... 0.         0.         0.        ]
 [0.09692383 0.14892578 0.01737976 ... 0.         0.         0.        ]
 ...
 [0.10638428 0.14929199 0.05245972 ... 0.         0.         0.        ]
 [0.14697266 0.1217041  0.02381897 ... 0.         0.         0.        ]
 [0.08758545 0.06634521 0.05599976 ... 0.         0.         0.3100586 ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.03622437 0.02212524 0.         ... 0.         0.         0.        ]
 [0.03515625 0.03781128 0.         ... 0.         0.         0.        ]
 [0.04644775 0.04962158 0.02027893 ... 0.         0.         0.        ]
 ...
 [0.01373291 0.01374817 0.         ... 0.         0.         0.        ]
 [0.03186035 0.02122498 0.         ... 0.         0.         0.        ]
 [0.0862426

  9%|▉         | 23/256 [00:01<00:14, 16.63it/s]

tf.Tensor([0 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.05325317 0.03561401 0.14550781 ... 0.         0.         0.        ]
 [0.05072021 0.07501221 0.0484314  ... 0.         0.         0.        ]
 [0.0294342  0.05990601 0.07952881 ... 0.         0.         0.        ]
 ...
 [0.04281616 0.03662109 0.00820923 ... 0.14221191 0.         0.04901123]
 [0.05252075 0.0380249  0.12939453 ... 0.09924316 0.         0.17358398]
 [0.02746582 0.02330017 0.04006958 ... 0.04269409 0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([1 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.03198242 0.0411377  0.06567383 ... 0.         0.         0.        ]
 [0.05853271 0.06628418 0.0218811  ... 0.         0.         0.        ]
 [0.0362854  0.04370117 0.03347778 ... 0.         0.         0.        ]
 ...
 [0.00570297 0.00042963 0.         ... 0.         0.         0.        ]
 [0.02069092 0.00847626 0.         ... 0.         0.         0.14221191]
 [0.0308990

 11%|█         | 27/256 [00:01<00:13, 17.14it/s]

tf.Tensor([0 0 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.00675964 0.01954651 0.         ... 0.         0.         0.        ]
 [0.00105667 0.00107384 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.01860046 0.00617599 0.         ... 0.         0.         0.        ]
 [0.03363037 0.01235199 0.         ... 0.         0.         0.        ]
 [0.05722046 0.05691528 0.13513184 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 1 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.05783081 0.11621094 0.20263672 ... 0.18005371 0.         0.        ]
 [0.06921387 0.0635376  0.0703125  ... 0.13049316 0.         0.        ]
 [0.07958984 0.06988525 0.13745117 ... 0.         0.         0.        ]
 ...
 [0.034729   0.06054688 0.         ... 0.         0.         0.02459717]
 [0.03778076 0.05099487 0.01239014 ... 0.         0.         0.        ]
 [0.0374145

 12%|█▏        | 31/256 [00:01<00:13, 16.71it/s]

tf.Tensor([0 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.02590942 0.03320312 0.         ... 0.         0.         0.        ]
 [0.0186615  0.01287079 0.         ... 0.         0.         0.05953979]
 [0.03274536 0.01424408 0.         ... 0.31103516 0.         0.        ]
 ...
 [0.04562378 0.08453369 0.0297699  ... 0.         0.         0.        ]
 [0.08154297 0.03056335 0.03942871 ... 0.         0.         0.        ]
 [0.05889893 0.06384277 0.08081055 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([1 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.06970215 0.07336426 0.03765869 ... 0.         0.         0.        ]
 [0.0925293  0.09893799 0.         ... 0.         0.         0.        ]
 [0.06536865 0.04519653 0.01722717 ... 0.         0.         0.        ]
 ...
 [0.04290771 0.02893066 0.         ... 0.         0.         0.        ]
 [0.04388428 0.04229736 0.01062012 ... 0.         0.         0.04888916]
 [0.0640869

 14%|█▎        | 35/256 [00:02<00:13, 16.72it/s]

tf.Tensor([0 1 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.02586365 0.02960205 0.         ... 0.         0.         0.        ]
 [0.08483887 0.06033325 0.01319885 ... 0.         0.         0.        ]
 [0.12017822 0.12536621 0.0352478  ... 0.         0.         0.        ]
 ...
 [0.14855957 0.07501221 0.09674072 ... 0.         0.         0.        ]
 [0.13842773 0.07330322 0.12005615 ... 0.         0.         0.        ]
 [0.13977051 0.10638428 0.13513184 ... 0.48217773 0.09606934 0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([1 0 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.0173645  0.01084137 0.07049561 ... 0.         0.         0.        ]
 [0.04522705 0.05514526 0.2607422  ... 0.         0.         0.        ]
 [0.06689453 0.08349609 0.265625   ... 0.         0.         0.        ]
 ...
 [0.08105469 0.1505127  0.01448059 ... 0.         0.         0.        ]
 [0.08319092 0.09466553 0.04119873 ... 0.         0.         0.        ]
 [0.0986328

 15%|█▌        | 39/256 [00:02<00:12, 17.01it/s]

tf.Tensor([0 0 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.05810547 0.03503418 0.00193119 ... 0.         0.         0.1887207 ]
 [0.05987549 0.03546143 0.05697632 ... 0.         0.2290039  0.        ]
 [0.06524658 0.02140808 0.1508789  ... 0.         0.2541504  0.        ]
 ...
 [0.08843994 0.04690552 0.01577759 ... 0.         0.         0.        ]
 [0.03811646 0.06192017 0.01512909 ... 0.         0.         0.        ]
 [0.04016113 0.09906006 0.05343628 ... 0.03939819 0.         0.05465698]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 1 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.00253487 0.00472641 0.         ... 0.         0.         0.        ]
 [0.02375793 0.01222229 0.         ... 0.         0.         0.13891602]
 ...
 [0.02609253 0.00022876 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.0204772

 17%|█▋        | 43/256 [00:02<00:13, 15.89it/s]

tf.Tensor([0 1 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.04290771 0.05587769 0.10797119 ... 0.         0.         0.47729492]
 [0.02552795 0.0456543  0.02349854 ... 1.9658203  0.         0.        ]
 [0.05969238 0.03363037 0.02478027 ... 0.         0.         0.        ]
 ...
 [0.05557251 0.01374817 0.         ... 0.         0.         0.        ]
 [0.03494263 0.00950623 0.         ... 0.         0.         0.        ]
 [0.04495239 0.03408813 0.02253723 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.06433105 0.040802   0.0859375  ... 0.         0.03089905 0.        ]
 [0.17578125 0.16601562 0.3005371  ... 0.         0.         0.        ]
 [0.1583252  0.3083496  0.06951904 ... 0.         0.03747559 0.        ]
 ...
 [0.09075928 0.05117798 0.05407715 ... 0.         0.         0.        ]
 [0.16003418 0.10217285 0.02896118 ... 0.0960083  0.         0.        ]
 [0.0866088

 18%|█▊        | 47/256 [00:02<00:13, 15.85it/s]

tf.Tensor([0 0 1 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.03799438 0.00718307 0.05953979 ... 0.         0.         0.        ]
 [0.03053284 0.04147339 0.0297699  ... 0.         0.17980957 0.        ]
 [0.04888916 0.04180908 0.04650879 ... 0.         0.         0.        ]
 ...
 [0.03016663 0.00961304 0.         ... 0.         0.         0.        ]
 [0.06665039 0.00791931 0.0791626  ... 0.         0.         0.        ]
 [0.05157471 0.01540375 0.01094055 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.07208252 0.07507324 0.0218811  ... 0.         0.         0.        ]
 [0.04284668 0.04177856 0.05987549 ... 0.         0.         0.        ]
 [0.06896973 0.04998779 0.09460449 ... 0.         0.         0.        ]
 ...
 [0.07067871 0.04446411 0.00482941 ... 0.         0.         0.        ]
 [0.06079102 0.052948   0.03411865 ... 0.         0.         0.        ]
 [0.0341491

KeyboardInterrupt: 

In [52]:
options = tf.io.TFRecordOptions(compression_type="ZLIB")
# tfr_output_filename_2 = tfr_output_filename+'2'
with tf.io.TFRecordWriter(tfr_output_filename,options=options) as writer:
    for sequence,targets in tqdm(parsed_dataset,total=256):
#         print(targets.shape,type(targets))
        new_targets = tf.zeros((896,5313))
#         print(new_targets.shape,type(new_targets))
        example = serialize_example(sequence,new_targets)
#         print(example.SerializeToString()[0:100])
        writer.write(example.SerializeToString())

100%|██████████| 256/256 [00:36<00:00,  6.95it/s]


In [42]:
new_dataset = tf.data.TFRecordDataset(tfr_output_filename,compression_type='ZLIB')
new_parsed_dataset = new_dataset.map(parser.parse_proto)    

In [43]:
for sequence,targets in tqdm(new_parsed_dataset,total=256):
    print(sequence,targets)

  1%|          | 3/256 [00:00<00:21, 12.02it/s]

tf.Tensor([0 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.07519531 0.01112366 0.01609802 ... 0.         0.         0.        ]
 [0.0881958  0.01392365 0.03829956 ... 0.         0.         0.        ]
 [0.05108643 0.01622009 0.01737976 ... 0.         0.         0.        ]
 ...
 [0.00142574 0.001544   0.         ... 0.         0.         0.        ]
 [0.00675964 0.         0.         ... 0.         0.         0.        ]
 [0.05609131 0.0559082  0.06762695 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.06958008 0.06192017 0.         ... 0.14208984 0.         0.        ]
 [0.06665039 0.0425415  0.03186035 ... 0.         0.         0.19018555]
 [0.04772949 0.01244354 0.01963806 ... 0.         0.         0.        ]
 ...
 [0.09320068 0.06671143 0.         ... 0.         0.         0.        ]
 [0.09973145 0.03692627 0.01110077 ... 0.         0.         0.        ]
 [0.0589294

  3%|▎         | 7/256 [00:00<00:15, 15.96it/s]

tf.Tensor([0 0 1 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.08758545 0.1607666  0.10845947 ... 0.         0.         0.        ]
 [0.07965088 0.0758667  0.04248047 ... 0.         0.         0.        ]
 [0.06768799 0.05587769 0.05859375 ... 0.         0.         0.        ]
 ...
 [0.1071167  0.1348877  0.28125    ... 0.17297363 0.         0.        ]
 [0.08081055 0.0949707  0.18603516 ... 0.         0.         0.        ]
 [0.11560059 0.15039062 0.2631836  ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 1 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.0574646  0.06378174 0.01029968 ... 0.         0.         0.        ]
 [0.0047226  0.0048027  0.         ... 0.         0.         0.        ]
 [0.03335571 0.03765869 0.02542114 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00190163 0.00617599 0.         ... 0.         0.         0.        ]
 [0.0082855

  4%|▍         | 11/256 [00:00<00:14, 16.55it/s]

tf.Tensor([0 0 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.06628418 0.02578735 0.01577759 ... 0.         0.         0.        ]
 [0.06365967 0.02326965 0.00997925 ... 0.         0.22692871 0.        ]
 [0.0446167  0.01660156 0.         ... 0.         0.         0.        ]
 ...
 [0.14038086 0.12817383 0.16833496 ... 0.0484314  0.3630371  0.13830566]
 [0.14611816 0.1229248  0.26513672 ... 0.         0.         0.        ]
 [0.07183838 0.10620117 0.33422852 ... 0.         0.05123901 0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([1 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.04174805 0.09460449 0.01078033 ... 0.         0.         0.        ]
 [0.03695679 0.01745605 0.         ... 0.07928467 0.         0.        ]
 [0.04675293 0.02781677 0.         ... 0.         0.         0.        ]
 ...
 [0.03897095 0.10272217 0.04650879 ... 0.         0.         2.3945312 ]
 [0.0345459  0.03814697 0.         ... 0.         0.         0.        ]
 [0.0434265

  6%|▌         | 15/256 [00:00<00:13, 17.33it/s]

tf.Tensor([1 0 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.05813599 0.1116333  0.17333984 ... 0.         0.         0.        ]
 [0.01287079 0.0174408  0.00209236 ... 0.         0.         0.        ]
 [0.00137806 0.0026207  0.00466537 ... 0.         0.         0.        ]
 ...
 [0.02545166 0.05108643 0.05407715 ... 0.         0.         0.        ]
 [0.00894928 0.01315308 0.         ... 0.         0.         0.        ]
 [0.02297974 0.02984619 0.         ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.18054199 0.08532715 0.19506836 ... 0.         0.02464294 0.        ]
 [0.18054199 0.07080078 0.23205566 ... 0.20910645 0.30786133 0.5341797 ]
 [0.21813965 0.09387207 0.3251953  ... 0.         0.         0.        ]
 ...
 [0.8413086  0.72216797 0.41503906 ... 0.         0.03955078 0.97509766]
 [0.85058594 0.38745117 0.3869629  ... 0.         0.05856323 0.        ]
 [1.8291016

  7%|▋         | 19/256 [00:01<00:13, 17.10it/s]

tf.Tensor([0 1 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.06445312 0.034729   0.02059937 ... 0.         0.         0.        ]
 [0.11181641 0.06604004 0.03121948 ... 0.         0.         0.        ]
 [0.09692383 0.14892578 0.01737976 ... 0.         0.         0.        ]
 ...
 [0.10638428 0.14929199 0.05245972 ... 0.         0.         0.        ]
 [0.14697266 0.1217041  0.02381897 ... 0.         0.         0.        ]
 [0.08758545 0.06634521 0.05599976 ... 0.         0.         0.3100586 ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.03622437 0.02212524 0.         ... 0.         0.         0.        ]
 [0.03515625 0.03781128 0.         ... 0.         0.         0.        ]
 [0.04644775 0.04962158 0.02027893 ... 0.         0.         0.        ]
 ...
 [0.01373291 0.01374817 0.         ... 0.         0.         0.        ]
 [0.03186035 0.02122498 0.         ... 0.         0.         0.        ]
 [0.0862426

  9%|▉         | 23/256 [00:01<00:14, 16.20it/s]

tf.Tensor([0 1 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.06817627 0.08129883 0.05438232 ... 0.         0.         0.        ]
 [0.0647583  0.03134155 0.0949707  ... 0.         0.         0.        ]
 [0.08905029 0.05053711 0.0508728  ... 0.         0.         0.        ]
 ...
 [0.05706787 0.03771973 0.05020142 ... 0.         0.         0.        ]
 [0.06774902 0.03991699 0.03378296 ... 0.         0.         0.        ]
 [0.06762695 0.07055664 0.02784729 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.05325317 0.03561401 0.14550781 ... 0.         0.         0.        ]
 [0.05072021 0.07501221 0.0484314  ... 0.         0.         0.        ]
 [0.0294342  0.05990601 0.07952881 ... 0.         0.         0.        ]
 ...
 [0.04281616 0.03662109 0.00820923 ... 0.14221191 0.         0.04901123]
 [0.05252075 0.0380249  0.12939453 ... 0.09924316 0.         0.17358398]
 [0.0274658

 11%|█         | 27/256 [00:01<00:14, 16.35it/s]

tf.Tensor([0 1 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.14929199 0.1673584  0.09014893 ... 0.         0.         0.        ]
 [0.17077637 0.2602539  0.06842041 ... 0.         0.         0.        ]
 [0.15014648 0.20983887 0.         ... 0.         0.         0.        ]
 ...
 [0.21142578 0.2705078  0.3708496  ... 0.         0.         0.        ]
 [0.24829102 0.31884766 0.31201172 ... 0.         0.         0.        ]
 [0.22253418 0.29760742 0.26782227 ... 0.         0.11877441 0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.00675964 0.01954651 0.         ... 0.         0.         0.        ]
 [0.00105667 0.00107384 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.01860046 0.00617599 0.         ... 0.         0.         0.        ]
 [0.03363037 0.01235199 0.         ... 0.         0.         0.        ]
 [0.0572204

 12%|█▏        | 31/256 [00:01<00:13, 16.61it/s]

tf.Tensor([0 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.00375938 0.         ... 0.         0.         0.        ]
 [0.04623413 0.01009369 0.03155518 ... 0.         0.         0.        ]
 ...
 [0.08734131 0.06329346 0.00225258 ... 0.         0.         0.        ]
 [0.06063843 0.09472656 0.00675964 ... 0.         0.         0.        ]
 [0.04125977 0.08221436 0.06115723 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.02590942 0.03320312 0.         ... 0.         0.         0.        ]
 [0.0186615  0.01287079 0.         ... 0.         0.         0.05953979]
 [0.03274536 0.01424408 0.         ... 0.31103516 0.         0.        ]
 ...
 [0.04562378 0.08453369 0.0297699  ... 0.         0.         0.        ]
 [0.08154297 0.03056335 0.03942871 ... 0.         0.         0.        ]
 [0.0588989

 14%|█▎        | 35/256 [00:02<00:13, 16.56it/s]

tf.Tensor([0 1 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.06628418 0.02740479 0.09960938 ... 0.         0.         0.        ]
 [0.09362793 0.07641602 0.10284424 ... 0.         0.         0.        ]
 [0.04171753 0.07434082 0.02059937 ... 0.         0.02967834 0.        ]
 ...
 [0.09332275 0.05282593 0.10955811 ... 0.         0.         0.        ]
 [0.06866455 0.02615356 0.09204102 ... 0.         0.         0.        ]
 [0.06414795 0.03182983 0.08898926 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 1 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.02586365 0.02960205 0.         ... 0.         0.         0.        ]
 [0.08483887 0.06033325 0.01319885 ... 0.         0.         0.        ]
 [0.12017822 0.12536621 0.0352478  ... 0.         0.         0.        ]
 ...
 [0.14855957 0.07501221 0.09674072 ... 0.         0.         0.        ]
 [0.13842773 0.07330322 0.12005615 ... 0.         0.         0.        ]
 [0.1397705

 15%|█▌        | 39/256 [00:02<00:12, 16.73it/s]

tf.Tensor([0 0 1 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.1340332  0.10900879 0.14294434 ... 0.         0.         0.        ]
 [0.11138916 0.10754395 0.08758545 ... 0.         0.         0.        ]
 [0.12231445 0.13623047 0.09143066 ... 0.         0.         0.        ]
 ...
 [0.13574219 0.0960083  0.12036133 ... 0.00704956 0.         0.        ]
 [0.09698486 0.04818726 0.04504395 ... 0.1348877  0.         0.        ]
 [0.03991699 0.00727844 0.         ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.05810547 0.03503418 0.00193119 ... 0.         0.         0.1887207 ]
 [0.05987549 0.03546143 0.05697632 ... 0.         0.2290039  0.        ]
 [0.06524658 0.02140808 0.1508789  ... 0.         0.2541504  0.        ]
 ...
 [0.08843994 0.04690552 0.01577759 ... 0.         0.         0.        ]
 [0.03811646 0.06192017 0.01512909 ... 0.         0.         0.        ]
 [0.0401611

 17%|█▋        | 43/256 [00:02<00:12, 16.71it/s]

tf.Tensor([0 0 1 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.11962891 0.04367065 0.         ... 0.         0.         0.        ]
 [0.11883545 0.05697632 0.00611496 ... 0.         0.         0.07781982]
 [0.04211426 0.03942871 0.01963806 ... 0.         0.         0.        ]
 ...
 [0.05743408 0.03491211 0.15454102 ... 0.         0.05020142 0.        ]
 [0.03692627 0.04211426 0.07659912 ... 0.         0.         0.        ]
 [0.05639648 0.04406738 0.07757568 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 1 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.04290771 0.05587769 0.10797119 ... 0.         0.         0.47729492]
 [0.02552795 0.0456543  0.02349854 ... 1.9658203  0.         0.        ]
 [0.05969238 0.03363037 0.02478027 ... 0.         0.         0.        ]
 ...
 [0.05557251 0.01374817 0.         ... 0.         0.         0.        ]
 [0.03494263 0.00950623 0.         ... 0.         0.         0.        ]
 [0.0449523

 18%|█▊        | 47/256 [00:02<00:12, 17.02it/s]

tf.Tensor([0 1 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.02903748 0.04238892 0.18029785 ... 0.         0.         0.        ]
 [0.05148315 0.09387207 0.06500244 ... 0.         0.         0.        ]
 [0.01727295 0.01838684 0.02059937 ... 0.         0.         0.        ]
 ...
 [0.10980225 0.05560303 0.02059937 ... 0.         0.         0.        ]
 [0.09240723 0.09838867 0.         ... 0.         0.07556152 0.02488708]
 [0.09625244 0.09881592 0.02124023 ... 0.         0.         0.03961182]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 1 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.03799438 0.00718307 0.05953979 ... 0.         0.         0.        ]
 [0.03053284 0.04147339 0.0297699  ... 0.         0.17980957 0.        ]
 [0.04888916 0.04180908 0.04650879 ... 0.         0.         0.        ]
 ...
 [0.03016663 0.00961304 0.         ... 0.         0.         0.        ]
 [0.06665039 0.00791931 0.0791626  ... 0.         0.         0.        ]
 [0.0515747

 20%|█▉        | 51/256 [00:03<00:12, 16.91it/s]

tf.Tensor([1 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.0425415  0.01786804 0.         ... 0.         0.         0.        ]
 [0.02523804 0.02479553 0.09783936 ... 0.         0.         0.        ]
 [0.03671265 0.01953125 0.13842773 ... 0.         0.         0.        ]
 ...
 [0.05422974 0.06124878 0.0186615  ... 0.         0.         0.        ]
 [0.0491333  0.02377319 0.         ... 0.         0.         0.        ]
 [0.05136108 0.02246094 0.         ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([1 0 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.06964111 0.03027344 0.         ... 0.         0.         0.        ]
 [0.08190918 0.02185059 0.04507446 ... 0.         0.         0.        ]
 [0.08422852 0.03060913 0.04827881 ... 0.         0.         0.        ]
 ...
 [0.04550171 0.03079224 0.         ... 0.         0.         0.05953979]
 [0.04437256 0.01864624 0.         ... 0.         0.         0.        ]
 [0.0256652

 21%|██▏       | 55/256 [00:03<00:12, 16.23it/s]

tf.Tensor([1 0 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.05438232 0.00616837 0.03555298 ... 0.         0.         0.        ]
 [0.07006836 0.02438354 0.05648804 ... 0.         0.         0.        ]
 [0.04324341 0.0284729  0.00547028 ... 0.         0.         0.        ]
 ...
 [0.05236816 0.04870605 0.         ... 0.         0.47509766 0.04998779]
 [0.07995605 0.08306885 0.06036377 ... 0.         0.         0.        ]
 [0.05358887 0.08746338 0.09576416 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([1 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.18139648 0.12524414 0.12988281 ... 0.         0.         0.        ]
 [0.13635254 0.08013916 0.17321777 ... 0.         0.         0.        ]
 [0.11120605 0.06115723 0.09527588 ... 0.         0.         0.        ]
 ...
 [0.03881836 0.08062744 0.01544952 ... 0.         0.         0.        ]
 [0.04537964 0.0188446  0.08319092 ... 0.         0.         0.        ]
 [0.0104141

 23%|██▎       | 59/256 [00:03<00:11, 16.93it/s]

tf.Tensor([0 0 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.0176239  0.04104614 0.0177002  ... 0.         0.         0.        ]
 [0.01046753 0.01538086 0.03186035 ... 0.         0.         0.34838867]
 [0.         0.0041008  0.         ... 0.         0.         0.        ]
 ...
 [0.05368042 0.0512085  0.0008049  ... 0.         0.         0.        ]
 [0.04037476 0.05578613 0.02059937 ... 0.         0.         0.05957031]
 [0.02453613 0.03607178 0.01737976 ... 0.         0.         0.09277344]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 1 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.03311157 0.01728821 0.02043152 ... 0.11358643 0.4951172  1.1601562 ]
 [0.03738403 0.01482391 0.         ... 0.         0.         0.        ]
 [0.02937317 0.0456543  0.         ... 0.         0.         0.        ]
 ...
 [0.08453369 0.09570312 0.15319824 ... 0.         0.         0.        ]
 [0.09710693 0.10601807 0.08465576 ... 0.         0.         0.1328125 ]
 [0.0981445

 25%|██▍       | 63/256 [00:03<00:11, 16.82it/s]

tf.Tensor([1 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.00675964 0.         0.         ... 0.         0.07952881 0.        ]
 [0.0014782  0.00543213 0.0120697  ... 0.         0.         0.        ]
 [0.00675964 0.02655029 0.05551147 ... 0.         0.06137085 0.        ]
 ...
 [0.07147217 0.09490967 0.17443848 ... 0.         0.         0.        ]
 [0.02037048 0.01377869 0.03491211 ... 0.         0.         0.        ]
 [0.01675415 0.00794983 0.02140808 ... 0.         0.         0.09570312]], shape=(896, 5313), dtype=float32)
tf.Tensor([1 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.05905151 0.10192871 0.05166626 ... 0.         0.         0.        ]
 [0.0826416  0.06057739 0.05505371 ... 0.         0.         0.        ]
 [0.0713501  0.0244751  0.14929199 ... 0.         0.         0.        ]
 ...
 [0.04486084 0.02970886 0.         ... 0.11584473 0.         0.        ]
 [0.02374268 0.01552582 0.         ... 0.         0.02667236 0.        ]
 [0.0068435

 26%|██▌       | 67/256 [00:04<00:11, 16.81it/s]

tf.Tensor([1 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.07653809 0.10522461 0.14208984 ... 0.         0.29345703 0.        ]
 [0.10852051 0.08856201 0.01963806 ... 0.         0.48095703 0.        ]
 [0.03796387 0.02363586 0.         ... 0.         0.         0.        ]
 ...
 [0.08361816 0.0562439  0.02703857 ... 0.         0.         0.31152344]
 [0.10559082 0.1104126  0.15563965 ... 0.         0.         0.        ]
 [0.04800415 0.09429932 0.0748291  ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 1 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.01731873 0.016922   0.01931763 ... 0.         0.         0.48291016]
 [0.02172852 0.0276947  0.00643921 ... 0.         0.15539551 0.        ]
 [0.02330017 0.03262329 0.         ... 0.         0.         0.48266602]
 ...
 [0.0271759  0.08459473 0.01544952 ... 0.         0.         0.        ]
 [0.02742004 0.03546143 0.03863525 ... 0.         0.         0.        ]
 [0.0202789

 28%|██▊       | 71/256 [00:04<00:11, 16.71it/s]

tf.Tensor([0 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[3.9794922e-02 1.5419006e-02 4.5074463e-02 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [1.0561943e-04 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [1.4259338e-02 3.8330078e-02 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 ...
 [3.8299561e-02 2.2399902e-02 2.0599365e-02 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [6.4331055e-02 5.6427002e-02 4.5051575e-03 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [9.6801758e-02 6.8481445e-02 2.3498535e-02 ... 0.0000000e+00
  0.0000000e+00 1.6406250e-01]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.06610107 0.05487061 0.01448059 ... 0.07147217 0.         0.        ]
 [0.07891846 0.05252075 0.0199585  ... 0.         0.9838867  0.        ]
 [0.08233643 0.05941772 0.14416504 ... 0.         1.5488281  0.        ]
 ...
 [0.00970459 0.00856781 0.         ..

 29%|██▉       | 75/256 [00:04<00:10, 16.74it/s]

tf.Tensor([0 1 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.08154297 0.04916382 0.09399414 ... 0.         0.         0.        ]
 [0.05297852 0.03048706 0.02703857 ... 0.31103516 0.         0.        ]
 [0.04968262 0.05334473 0.01303864 ... 0.         0.         0.        ]
 ...
 [0.05249023 0.00402832 0.01174927 ... 0.         0.         0.        ]
 [0.0456543  0.00794983 0.01979065 ... 0.         0.         0.        ]
 [0.02497864 0.0117569  0.00273514 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([1 0 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.         0.00687408 0.         ... 0.         0.         0.        ]
 [0.02784729 0.01803589 0.0231781  ... 0.         0.         0.        ]
 [0.06658936 0.11541748 0.05407715 ... 0.         0.48168945 0.        ]
 ...
 [0.07324219 0.07745361 0.03509521 ... 0.         0.         0.        ]
 [0.04553223 0.04696655 0.03991699 ... 0.         0.         0.        ]
 [0.0588378

 30%|███       | 77/256 [00:04<00:10, 16.73it/s]

tf.Tensor([0 0 1 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.01436615 0.02145386 0.         ... 0.         0.         0.        ]
 [0.01579285 0.01268005 0.         ... 0.         0.         0.        ]
 [0.0015316  0.         0.         ... 0.         0.         0.        ]
 ...
 [0.05975342 0.05187988 0.         ... 0.         0.         0.        ]
 [0.05337524 0.05050659 0.         ... 0.         0.         0.        ]
 [0.03427124 0.05075073 0.13586426 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([1 0 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.05657959 0.06860352 0.03765869 ... 0.         0.         0.        ]
 [0.05184937 0.02827454 0.03283691 ... 0.         0.         0.        ]
 [0.03997803 0.03759766 0.05166626 ... 0.         0.         0.        ]
 ...
 [0.05758667 0.05355835 0.         ... 0.         0.         0.04058838]
 [0.01177216 0.03781128 0.14160156 ... 0.         0.         0.2861328 ]
 [0.0237884

 32%|███▏      | 81/256 [00:04<00:10, 16.10it/s]

tf.Tensor([0 0 1 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.01579285 0.02331543 0.         ... 0.         0.         0.        ]
 [0.03096008 0.04898071 0.09173584 ... 0.         0.         0.        ]
 [0.00315094 0.02536011 0.02093506 ... 0.         0.         0.        ]
 ...
 [0.08959961 0.11071777 0.01448059 ... 0.         0.         0.        ]
 [0.07769775 0.09667969 0.02027893 ... 0.         0.         0.        ]
 [0.11816406 0.12561035 0.11138916 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 1 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.15722656 0.1842041  0.1920166  ... 0.         0.         0.        ]
 [0.12145996 0.07006836 0.06115723 ... 0.         0.         0.        ]
 [0.01441193 0.00551987 0.         ... 0.         0.         0.        ]
 ...
 [0.13476562 0.18469238 0.50390625 ... 0.         0.         0.        ]
 [0.14282227 0.1842041  0.25683594 ... 0.         0.         0.        ]
 [0.1649169

 33%|███▎      | 85/256 [00:05<00:10, 16.39it/s]

tf.Tensor([0 1 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.00341606 0.0011816  0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.04818726 0.05337524 0.         ... 0.         0.         0.        ]
 [0.05383301 0.04162598 0.         ... 0.         0.         0.        ]
 [0.01544952 0.00452423 0.         ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.06665039 0.01972961 0.01222992 ... 0.         0.         0.        ]
 [0.07080078 0.01731873 0.         ... 0.22802734 0.10748291 0.        ]
 [0.07440186 0.04522705 0.         ... 0.         0.8911133  0.56689453]
 ...
 [0.05114746 0.07165527 0.01673889 ... 0.         0.         0.        ]
 [0.0287323  0.02287292 0.         ... 0.         0.         0.        ]
 [0.037323 

 35%|███▍      | 89/256 [00:05<00:10, 16.20it/s]

tf.Tensor([0 0 1 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.11151123 0.2076416  0.09918213 ... 0.         0.         0.        ]
 [0.10546875 0.18981934 0.03250122 ... 0.         0.         0.        ]
 [0.14465332 0.18530273 0.0440979  ... 0.         0.         0.        ]
 ...
 [0.20800781 0.27929688 0.07403564 ... 0.         0.         0.04037476]
 [0.15771484 0.35253906 0.27172852 ... 0.         0.         0.        ]
 [0.15979004 0.35083008 0.1751709  ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 1 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.06744385 0.03738403 0.01222992 ... 0.         0.         0.        ]
 [0.09289551 0.03939819 0.05020142 ... 0.         0.         0.        ]
 [0.07055664 0.04852295 0.00514984 ... 0.         0.         0.        ]
 ...
 [0.01828003 0.00310516 0.         ... 0.         0.         0.        ]
 [0.01478577 0.02684021 0.         ... 0.         0.         0.        ]
 [0.       

 36%|███▋      | 93/256 [00:05<00:09, 16.90it/s]

tf.Tensor([1 0 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.03427124 0.01095581 0.         ... 0.         0.         0.        ]
 [0.01055908 0.0038662  0.         ... 0.         0.         0.        ]
 [0.01311493 0.05639648 0.         ... 0.         0.         0.        ]
 ...
 [0.08538818 0.06695557 0.13659668 ... 0.05947876 0.         0.        ]
 [0.09130859 0.06222534 0.05810547 ... 0.         0.         0.        ]
 [0.04544067 0.02714539 0.0177002  ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 1 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.04873657 0.020401   0.         ... 0.         0.         0.        ]
 [0.03216553 0.021698   0.         ... 0.         0.         0.        ]
 [0.00991058 0.00246048 0.         ... 0.         0.         0.        ]
 ...
 [0.01828003 0.05819702 0.01029968 ... 0.         0.04202271 0.        ]
 [0.05053711 0.11608887 0.04119873 ... 0.         0.         0.        ]
 [0.0100326

 38%|███▊      | 97/256 [00:05<00:09, 17.18it/s]

tf.Tensor([0 0 1 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.06500244 0.05523682 0.15710449 ... 0.         0.         0.        ]
 [0.07055664 0.04238892 0.03411865 ... 0.         0.         0.        ]
 [0.04299927 0.04177856 0.14294434 ... 0.         0.         0.        ]
 ...
 [0.06161499 0.10009766 0.13452148 ... 0.         0.97802734 0.        ]
 [0.0508728  0.10247803 0.06951904 ... 0.         0.         0.        ]
 [0.10461426 0.07983398 0.06439209 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 1 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.33154297 0.22680664 0.46142578 ... 0.         0.         0.        ]
 [0.29223633 0.20043945 0.5410156  ... 0.         0.         0.        ]
 [0.1887207  0.16247559 0.50097656 ... 0.         0.         0.        ]
 ...
 [0.15368652 0.25195312 0.22631836 ... 0.         0.         0.        ]
 [0.20422363 0.21569824 0.25024414 ... 0.         0.         0.        ]
 [0.2233886

 39%|███▉      | 101/256 [00:06<00:09, 16.98it/s]

tf.Tensor([1 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.01721191 0.05526733 0.09417725 ... 0.         0.08831787 0.        ]
 [0.01338196 0.02255249 0.         ... 0.         0.         0.        ]
 [0.         0.0324707  0.         ... 0.         0.         0.        ]
 ...
 [0.17687988 0.20593262 0.5498047  ... 0.         0.         0.        ]
 [0.08374023 0.16601562 0.24133301 ... 0.         0.         0.        ]
 [0.08178711 0.13598633 0.0925293  ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.2319336  0.1850586  0.02880859 ... 0.         0.         0.        ]
 [0.25146484 0.2154541  0.05859375 ... 0.         0.984375   0.        ]
 [0.17797852 0.16040039 0.14453125 ... 0.         0.         0.11541748]
 ...
 [0.01393127 0.00370598 0.         ... 0.         0.         0.        ]
 [0.01678467 0.04879761 0.02156067 ... 0.09594727 0.         0.        ]
 [0.0921630

 41%|████      | 105/256 [00:06<00:09, 16.71it/s]

tf.Tensor([0 1 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.08673096 0.12536621 0.07275391 ... 0.         0.21057129 0.        ]
 [0.0680542  0.11572266 0.03622437 ... 0.         0.         0.        ]
 [0.07757568 0.1151123  0.         ... 0.04885864 0.         0.        ]
 ...
 [0.00179768 0.00229263 0.         ... 0.         0.17590332 0.        ]
 [0.01081848 0.03588867 0.04022217 ... 0.         0.         0.        ]
 [0.11126709 0.14672852 0.15905762 ... 0.         0.         0.00303078]], shape=(896, 5313), dtype=float32)
tf.Tensor([1 0 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.06329346 0.10131836 0.00836945 ... 0.         0.         0.        ]
 [0.07073975 0.07141113 0.04119873 ... 0.         0.         0.        ]
 [0.03530884 0.02845764 0.01158905 ... 0.         0.         0.        ]
 ...
 [0.00502777 0.01256561 0.01512909 ... 0.         0.         0.        ]
 [0.00696182 0.01205444 0.01222992 ... 0.         0.         0.        ]
 [0.0556945

 43%|████▎     | 109/256 [00:06<00:08, 16.98it/s]

tf.Tensor([0 1 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.03848267 0.0869751  0.12487793 ... 0.         0.         0.        ]
 [0.04788208 0.03295898 0.0199585  ... 0.         0.         0.        ]
 [0.04367065 0.02441406 0.05987549 ... 0.         0.         0.        ]
 ...
 [0.05981445 0.05615234 0.02124023 ... 0.         0.         0.        ]
 [0.02638245 0.04907227 0.         ... 0.         0.         0.        ]
 [0.02383423 0.01081085 0.00514984 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.05154419 0.13293457 0.32763672 ... 0.         0.         0.        ]
 [0.10870361 0.23986816 0.51171875 ... 0.         0.         0.        ]
 [0.19873047 0.2565918  0.76953125 ... 0.         0.         0.        ]
 ...
 [0.08868408 0.11480713 0.24401855 ... 0.         0.         0.        ]
 [0.04824829 0.03488159 0.05697632 ... 0.         0.         0.        ]
 [0.0622253

 44%|████▍     | 113/256 [00:06<00:08, 17.09it/s]

tf.Tensor([0 1 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[1.75628662e-02 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [8.60595703e-03 5.37037849e-05 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.32064819e-02 8.84246826e-03 0.00000000e+00 ... 0.00000000e+00
  4.53369141e-01 0.00000000e+00]
 ...
 [1.49536133e-01 1.19995117e-01 1.15600586e-01 ... 0.00000000e+00
  0.00000000e+00 2.10693359e-01]
 [1.21337891e-01 1.25854492e-01 2.05993652e-02 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.24084473e-01 1.58569336e-01 2.41470337e-03 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 1 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.04003906 0.02185059 0.         ... 0.         0.         0.        ]
 [0.00095081 0.00205803 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 

 46%|████▌     | 117/256 [00:07<00:08, 16.06it/s]

tf.Tensor([0 1 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.1171875  0.06646729 0.11590576 ... 0.         0.         0.        ]
 [0.10595703 0.08880615 0.11798096 ... 0.         0.         0.07873535]
 [0.15332031 0.1262207  0.26293945 ... 0.         0.         0.        ]
 ...
 [0.10528564 0.09118652 0.09057617 ... 0.         0.         0.        ]
 [0.05484009 0.02900696 0.21313477 ... 0.         0.         0.        ]
 [0.01759338 0.00365448 0.00901031 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 1 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.05535889 0.05105591 0.08850098 ... 0.         0.         0.        ]
 [0.06860352 0.02407837 0.09429932 ... 0.         0.         0.        ]
 [0.0345459  0.02807617 0.0008049  ... 0.         0.         0.        ]
 ...
 [0.06033325 0.02374268 0.         ... 0.         0.11022949 0.        ]
 [0.04196167 0.0269928  0.02816772 ... 0.         0.         0.        ]
 [0.0526428

 47%|████▋     | 121/256 [00:07<00:08, 16.61it/s]

tf.Tensor([0 0 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.0236969  0.0086441  0.07403564 ... 0.         0.         0.        ]
 [0.00506973 0.01280975 0.01222992 ... 0.         0.         0.        ]
 [0.0272522  0.01210785 0.01416016 ... 0.         0.         0.        ]
 ...
 [0.02105713 0.0276947  0.05535889 ... 0.         0.         0.        ]
 [0.0294342  0.02626038 0.08886719 ... 0.         0.         0.3347168 ]
 [0.02677917 0.01911926 0.00643921 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 1 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.07019043 0.09655762 0.02253723 ... 0.         0.         0.        ]
 [0.08288574 0.06915283 0.03347778 ... 0.         0.         0.        ]
 [0.05212402 0.05548096 0.00965881 ... 0.         0.         0.        ]
 ...
 [0.04281616 0.01496887 0.         ... 0.         0.         0.01515198]
 [0.04504395 0.05252075 0.         ... 0.         0.42871094 0.02313232]
 [0.0458984

 49%|████▉     | 125/256 [00:07<00:08, 16.27it/s]

tf.Tensor([0 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.02111816 0.03033447 0.         ... 0.         0.         0.        ]
 [0.01696777 0.0236969  0.         ... 0.         0.         0.        ]
 [0.01815796 0.01103973 0.         ... 0.         0.         0.09619141]
 ...
 [0.02386475 0.03988647 0.         ... 0.         0.         0.        ]
 [0.05001831 0.02160645 0.         ... 0.         0.         0.        ]
 [0.04055786 0.02163696 0.         ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.09130859 0.05349731 0.0814209  ... 0.         0.         0.        ]
 [0.09307861 0.03497314 0.03701782 ... 0.         0.         0.        ]
 [0.04443359 0.01876831 0.01190948 ... 0.         0.         0.        ]
 ...
 [0.02487183 0.02235413 0.         ... 0.         0.         0.07946777]
 [0.03747559 0.05361938 0.01287842 ... 0.         0.         0.        ]
 [0.0858154

 50%|█████     | 129/256 [00:07<00:07, 16.35it/s]

tf.Tensor([0 0 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.17297363 0.07867432 0.02445984 ... 0.48266602 0.         0.        ]
 [0.11230469 0.09118652 0.03863525 ... 0.         0.         0.        ]
 [0.09893799 0.05072021 0.1538086  ... 0.         0.22802734 0.        ]
 ...
 [0.04421997 0.03268433 0.01158905 ... 0.         0.         0.        ]
 [0.05395508 0.04931641 0.         ... 0.         1.0478516  0.        ]
 [0.12780762 0.08496094 0.0231781  ... 0.         2.4238281  0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.03744507 0.03674316 0.06402588 ... 0.         0.         0.        ]
 [0.02246094 0.03744507 0.08691406 ... 0.         0.         0.        ]
 [0.00574875 0.03463745 0.01383972 ... 0.         0.         0.        ]
 ...
 [0.03729248 0.03204346 0.00225258 ... 0.         0.08441162 0.        ]
 [0.01792908 0.0385437  0.         ... 0.         0.         0.        ]
 [0.0417480

 52%|█████▏    | 133/256 [00:08<00:07, 16.67it/s]

tf.Tensor([0 0 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.11297607 0.06390381 0.10076904 ... 0.         0.         0.        ]
 [0.11102295 0.07415771 0.02156067 ... 0.         0.         0.        ]
 [0.1694336  0.06878662 0.13000488 ... 0.         0.         0.        ]
 ...
 [0.0027256  0.00300789 0.         ... 0.         0.         0.        ]
 [0.00701523 0.0164032  0.         ... 0.         0.         0.        ]
 [0.02697754 0.03091431 0.         ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.15185547 0.09759521 0.05535889 ... 0.         0.17626953 0.        ]
 [0.08453369 0.12329102 0.13562012 ... 0.         0.03741455 0.        ]
 [0.07263184 0.10626221 0.21228027 ... 0.         0.         0.        ]
 ...
 [0.00692749 0.00397491 0.         ... 0.         0.         0.        ]
 [0.05871582 0.05361938 0.0241394  ... 0.         0.         0.        ]
 [0.0954589

 54%|█████▎    | 137/256 [00:08<00:07, 16.41it/s]

tf.Tensor([0 0 1 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.0592041  0.11181641 0.03475952 ... 0.         0.         0.        ]
 [0.05691528 0.07495117 0.01416016 ... 0.         0.         0.        ]
 [0.08850098 0.081604   0.03155518 ... 0.         0.         0.        ]
 ...
 [0.00282669 0.00021482 0.         ... 0.         0.         0.        ]
 [0.00849915 0.01042175 0.         ... 0.         0.         0.        ]
 [0.00740051 0.01348114 0.         ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.05545044 0.04724121 0.         ... 0.         0.         0.17700195]
 [0.01745605 0.02510071 0.         ... 0.         0.         0.        ]
 [0.0378418  0.05508423 0.         ... 0.         0.         0.        ]
 ...
 [0.01246643 0.01208496 0.03475952 ... 0.03059387 0.         0.        ]
 [0.01255035 0.02545166 0.01158905 ... 0.         0.         0.        ]
 [0.0653076

 55%|█████▌    | 141/256 [00:08<00:07, 16.25it/s]

tf.Tensor([1 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.02571106 0.04141235 0.         ... 0.         0.         0.        ]
 [0.04992676 0.04101562 0.         ... 0.         0.         0.        ]
 [0.03561401 0.02041626 0.         ... 0.         0.         0.        ]
 ...
 [0.06567383 0.02026367 0.         ... 0.         0.984375   0.        ]
 [0.07080078 0.04556274 0.         ... 0.         0.         0.        ]
 [0.06378174 0.02182007 0.03041077 ... 0.         0.         0.11682129]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.05062866 0.06646729 0.06018066 ... 0.         0.         0.        ]
 [0.04986572 0.03295898 0.02027893 ... 0.         0.         0.        ]
 [0.02734375 0.02824402 0.         ... 0.         0.         0.        ]
 ...
 [0.02032471 0.00601578 0.         ... 0.         0.         0.        ]
 [0.01389313 0.00483322 0.         ... 0.         0.         0.        ]
 [0.0285186

 57%|█████▋    | 145/256 [00:08<00:06, 16.44it/s]

tf.Tensor([1 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.16503906 0.1418457  0.25634766 ... 0.9272461  0.4802246  0.07147217]
 [0.15490723 0.13110352 0.24304199 ... 0.         0.         0.        ]
 [0.13134766 0.24621582 0.05215454 ... 0.         0.         0.        ]
 ...
 [0.0770874  0.13391113 0.07678223 ... 0.         0.         0.03051758]
 [0.12512207 0.13232422 0.04748535 ... 0.         0.98291016 0.        ]
 [0.12115479 0.07550049 0.         ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.04116821 0.02825928 0.         ... 0.         0.         0.        ]
 [0.06860352 0.04595947 0.00708008 ... 0.         0.         0.        ]
 [0.11950684 0.06420898 0.0395813  ... 0.         0.         0.        ]
 ...
 [0.12487793 0.06311035 0.14196777 ... 0.         0.         0.        ]
 [0.10943604 0.05758667 0.11297607 ... 0.05950928 0.         0.        ]
 [0.0993652

 58%|█████▊    | 149/256 [00:09<00:06, 16.89it/s]

tf.Tensor([1 0 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.15234375 0.18383789 0.24890137 ... 0.         0.         0.        ]
 [0.19213867 0.15710449 0.2541504  ... 0.         0.         0.        ]
 [0.12322998 0.13049316 0.43969727 ... 0.         0.         0.        ]
 ...
 [0.3540039  0.24975586 0.35205078 ... 0.         0.         0.        ]
 [0.41015625 0.32055664 0.45507812 ... 0.         0.01130676 0.9785156 ]
 [0.34570312 0.29614258 0.35180664 ... 0.         0.06781006 0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([1 0 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.09832764 0.0539856  0.03637695 ... 0.         0.14221191 0.        ]
 [0.09912109 0.08190918 0.06082153 ... 0.         0.         0.        ]
 [0.06921387 0.05877686 0.0395813  ... 0.         0.         0.        ]
 ...
 [0.01133728 0.0073204  0.         ... 0.48217773 0.         0.        ]
 [0.01409149 0.01751709 0.         ... 0.         0.         0.        ]
 [0.025177 

 60%|█████▉    | 153/256 [00:09<00:06, 16.68it/s]

tf.Tensor([1 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.03997803 0.09814453 0.21472168 ... 0.         0.         0.        ]
 [0.0607605  0.0692749  0.1784668  ... 0.         0.         0.        ]
 [0.05203247 0.06060791 0.13989258 ... 0.         0.         0.        ]
 ...
 [0.0925293  0.17199707 0.0378418  ... 0.         0.         0.        ]
 [0.06292725 0.1126709  0.10559082 ... 0.         0.         0.        ]
 [0.08319092 0.09143066 0.02687073 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 1 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.00226593 0.01526642 0.01802063 ... 0.         0.         0.        ]
 [0.00923157 0.00710297 0.         ... 0.         0.         0.        ]
 [0.07318115 0.04388428 0.         ... 0.         0.         0.        ]
 ...
 [0.02883911 0.05343628 0.12487793 ... 0.         0.22839355 0.        ]
 [0.00686646 0.03674316 0.01673889 ... 0.         0.         0.        ]
 [0.       

 61%|██████▏   | 157/256 [00:09<00:05, 16.54it/s]

tf.Tensor([0 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.04541016 0.04348755 0.04684448 ... 0.         0.         0.        ]
 [0.05664062 0.02989197 0.01834106 ... 0.         0.         0.984375  ]
 [0.03817749 0.01701355 0.         ... 0.         0.         0.        ]
 ...
 [0.06161499 0.06488037 0.04425049 ... 0.         0.         0.        ]
 [0.07733154 0.03115845 0.03717041 ... 0.         0.         0.        ]
 [0.03210449 0.02316284 0.02671814 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([1 0 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.00697708 0.         0.02059937 ... 0.         0.         0.        ]
 [0.0035038  0.         0.00177002 ... 0.         0.         0.        ]
 [0.04321289 0.08978271 0.10858154 ... 0.04879761 0.         0.        ]
 ...
 [0.00345802 0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.       

 63%|██████▎   | 161/256 [00:09<00:05, 16.96it/s]

tf.Tensor([0 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.03372192 0.03533936 0.11395264 ... 0.         0.04873657 0.        ]
 [0.01568604 0.00375938 0.00643921 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.06640625 0.02896118 0.04119873 ... 0.         0.         0.        ]
 [0.01150513 0.00665665 0.00836945 ... 0.         0.         0.        ]
 [0.02630615 0.00537109 0.         ... 0.         0.30981445 0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([1 0 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.06002808 0.05587769 0.02575684 ... 0.         0.         0.        ]
 [0.06396484 0.11560059 0.01931763 ... 0.         0.         0.        ]
 [0.05078125 0.08044434 0.         ... 0.         0.         0.        ]
 ...
 [0.14099121 0.2705078  0.15966797 ... 0.         0.         0.        ]
 [0.10089111 0.18603516 0.12164307 ... 0.         0.         0.        ]
 [0.1630859

 64%|██████▍   | 165/256 [00:09<00:05, 16.88it/s]

tf.Tensor([0 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.05218506 0.05239868 0.02799988 ... 0.         0.         0.        ]
 [0.01972961 0.01756287 0.02027893 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.0637207  0.04910278 0.         ... 0.         0.         0.        ]
 [0.06390381 0.04464722 0.         ... 0.         0.         0.        ]
 [0.03384399 0.0189209  0.03041077 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([1 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.03689575 0.03588867 0.05020142 ... 0.         0.         0.        ]
 [0.065979   0.02612305 0.02880859 ... 0.         0.         0.        ]
 [0.05541992 0.03738403 0.0486145  ... 0.         0.         0.        ]
 ...
 [0.02577209 0.02738953 0.         ... 0.         0.         0.        ]
 [0.03106689 0.0073204  0.         ... 0.         0.         0.        ]
 [0.0330505

 66%|██████▌   | 169/256 [00:10<00:05, 17.13it/s]

tf.Tensor([0 0 1 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.08532715 0.05102539 0.02059937 ... 0.         0.         0.        ]
 [0.10632324 0.08496094 0.03025818 ... 0.         0.9814453  0.        ]
 [0.07324219 0.06045532 0.07434082 ... 0.         0.         0.22839355]
 ...
 [0.02549744 0.04037476 0.10424805 ... 0.         0.24035645 0.        ]
 [0.02307129 0.02680969 0.06726074 ... 0.         0.21569824 0.        ]
 [0.02409363 0.02648926 0.00675964 ... 0.         0.14172363 0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 1 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.03149414 0.01356506 0.0186615  ... 0.         0.         0.        ]
 [0.01424408 0.00450897 0.00450516 ... 0.         0.         0.        ]
 [0.04837036 0.01980591 0.04153442 ... 0.02203369 0.         0.        ]
 ...
 [0.06799316 0.08422852 0.14465332 ... 0.         0.         0.        ]
 [0.05734253 0.05163574 0.2265625  ... 0.         0.         0.        ]
 [0.0722045

 68%|██████▊   | 173/256 [00:10<00:04, 16.80it/s]

tf.Tensor([0 1 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.07519531 0.02116394 0.         ... 0.         0.         0.        ]
 [0.10479736 0.03482056 0.00273514 ... 0.         0.22790527 0.        ]
 [0.09411621 0.00961304 0.03509521 ... 0.         0.         0.        ]
 ...
 [0.037323   0.03790283 0.0072403  ... 0.01605225 0.         0.        ]
 [0.02894592 0.01914978 0.00579453 ... 0.         0.         0.        ]
 [0.14855957 0.06945801 0.06872559 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.00806427 0.01364899 0.         ... 0.         0.         0.        ]
 [0.00654984 0.         0.         ... 0.         0.         0.        ]
 [0.01299286 0.         0.         ... 0.         0.         0.        ]
 ...
 [0.04217529 0.04040527 0.         ... 0.         0.         0.        ]
 [0.03436279 0.01879883 0.         ... 0.         0.         0.14221191]
 [0.0489807

 69%|██████▉   | 177/256 [00:10<00:04, 17.04it/s]

tf.Tensor([0 1 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.08105469 0.07513428 0.01818848 ... 0.         0.11877441 0.        ]
 [0.06829834 0.08734131 0.         ... 0.         0.6328125  0.        ]
 [0.07568359 0.09429932 0.12866211 ... 0.         0.         0.        ]
 ...
 [0.05621338 0.0736084  0.05792236 ... 0.         0.         0.        ]
 [0.1060791  0.06115723 0.04989624 ... 0.         0.         0.        ]
 [0.06524658 0.03036499 0.01174927 ... 0.         0.04928589 0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 1 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.0736084  0.06008911 0.10076904 ... 0.0479126  0.         0.        ]
 [0.05270386 0.06219482 0.0748291  ... 0.17041016 0.         0.        ]
 [0.05627441 0.06256104 0.08630371 ... 0.         0.         0.        ]
 ...
 [0.03533936 0.03234863 0.11248779 ... 0.         0.         0.        ]
 [0.01019287 0.01277161 0.03460693 ... 0.         0.         0.        ]
 [0.0187530

 71%|███████   | 181/256 [00:10<00:04, 16.72it/s]

tf.Tensor([0 1 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.10437012 0.11981201 0.097229   ... 0.         0.         0.        ]
 [0.06433105 0.07305908 0.02575684 ... 0.         0.         0.        ]
 [0.00897217 0.00537109 0.         ... 0.         0.         0.        ]
 ...
 [0.21813965 0.2709961  0.17773438 ... 0.         0.         0.        ]
 [0.12524414 0.11450195 0.2775879  ... 0.         0.         0.        ]
 [0.12573242 0.14282227 0.40234375 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 1 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.00783539 0.         0.0352478  ... 0.         0.         0.22717285]
 [0.02059937 0.04098511 0.0617981  ... 0.         0.         0.        ]
 [0.0703125  0.09924316 0.05392456 ... 0.         0.         0.        ]
 ...
 [0.11694336 0.15576172 0.10028076 ... 0.         0.         0.1418457 ]
 [0.12658691 0.11346436 0.0703125  ... 0.         0.         0.        ]
 [0.1145629

 72%|███████▏  | 185/256 [00:11<00:04, 16.93it/s]

tf.Tensor([0 0 1 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.05889893 0.10900879 0.01158905 ... 0.         0.         0.        ]
 [0.09753418 0.12384033 0.14416504 ... 0.         0.         0.        ]
 [0.09790039 0.11566162 0.07659912 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.01277924 0.04776001 0.00579453 ... 0.         0.         0.14135742]
 [0.0647583  0.06365967 0.04763794 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.13049316 0.07720947 0.1081543  ... 0.         0.         0.        ]
 [0.05935669 0.03475952 0.18017578 ... 0.         0.09564209 0.        ]
 [0.07873535 0.03399658 0.081604   ... 0.         0.         0.        ]
 ...
 [0.07366943 0.05438232 0.02381897 ... 0.         0.         0.        ]
 [0.08288574 0.08294678 0.00820923 ... 0.         0.         0.        ]
 [0.0949707

 74%|███████▍  | 189/256 [00:11<00:03, 16.81it/s]

tf.Tensor([0 0 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.07641602 0.09503174 0.01303864 ... 0.         0.         0.        ]
 [0.07537842 0.09375    0.01528931 ... 0.         0.         0.        ]
 [0.03225708 0.02622986 0.00627518 ... 0.         0.         0.        ]
 ...
 [0.00931549 0.01381683 0.         ... 0.         0.         0.        ]
 [0.         0.00554657 0.         ... 0.         0.         0.        ]
 [0.03436279 0.046875   0.03555298 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 1 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.1394043  0.0736084  0.0120697  ... 0.         0.         0.        ]
 [0.08734131 0.07843018 0.02864075 ... 0.         0.         0.        ]
 [0.10638428 0.12371826 0.07513428 ... 0.         0.         0.        ]
 ...
 [0.04879761 0.05548096 0.16088867 ... 0.         0.         0.        ]
 [0.03019714 0.0456543  0.05569458 ... 0.         0.         0.        ]
 [0.1101684

 75%|███████▌  | 193/256 [00:11<00:03, 16.76it/s]

tf.Tensor([0 1 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.04333496 0.03341675 0.11712646 ... 0.         0.         0.        ]
 [0.05783081 0.0355835  0.04891968 ... 0.         0.         0.        ]
 [0.02337646 0.02253723 0.04473877 ... 0.         0.         0.        ]
 ...
 [0.08831787 0.05032349 0.03347778 ... 0.         0.         0.        ]
 [0.10974121 0.09008789 0.05697632 ... 0.26464844 0.05001831 0.90966797]
 [0.12695312 0.06268311 0.05020142 ... 0.         0.         0.11633301]], shape=(896, 5313), dtype=float32)
tf.Tensor([1 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.03131104 0.0463562  0.06036377 ... 0.         0.         0.        ]
 [0.01403046 0.02659607 0.01689148 ... 0.         0.         0.        ]
 [0.03314209 0.02359009 0.08129883 ... 0.         0.         0.        ]
 ...
 [0.01418304 0.         0.00788879 ... 0.         0.         0.        ]
 [0.00800323 0.00182629 0.02558899 ... 0.         0.         0.        ]
 [0.0130996

 77%|███████▋  | 197/256 [00:11<00:03, 16.63it/s]

tf.Tensor([0 0 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.08551025 0.10186768 0.06469727 ... 0.         0.         0.        ]
 [0.05770874 0.1541748  0.22277832 ... 0.         0.         0.09619141]
 [0.06195068 0.13781738 0.16625977 ... 0.         0.         0.        ]
 ...
 [0.41308594 0.29882812 0.296875   ... 0.         0.         0.        ]
 [0.3046875  0.2866211  0.22595215 ... 0.         0.         0.        ]
 [0.37573242 0.33569336 0.41918945 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 1 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.02812195 0.05810547 0.10046387 ... 0.         0.         0.        ]
 [0.04049683 0.08618164 0.03573608 ... 0.         0.         0.        ]
 [0.07073975 0.10150146 0.00675964 ... 0.11621094 0.         0.        ]
 ...
 [0.19274902 0.17468262 0.17895508 ... 0.         0.         0.        ]
 [0.2442627  0.16125488 0.09558105 ... 0.         0.11517334 0.        ]
 [0.1357421

 79%|███████▊  | 201/256 [00:12<00:03, 16.62it/s]

tf.Tensor([0 1 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.03500366 0.04660034 0.06939697 ... 0.         0.         0.        ]
 [0.04095459 0.06359863 0.07965088 ... 0.         0.         0.        ]
 [0.09320068 0.04943848 0.02929688 ... 0.         0.         0.        ]
 ...
 [0.10931396 0.10522461 0.17895508 ... 0.         0.         0.        ]
 [0.16540527 0.13586426 0.11895752 ... 0.         0.         0.        ]
 [0.1907959  0.15905762 0.04876709 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 1 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00893402 0.         0.         ... 0.         0.         0.        ]
 ...
 [0.1003418  0.17126465 0.22595215 ... 0.         0.         0.00338554]
 [0.09716797 0.1182251  0.11120605 ... 0.         0.984375   0.47875977]
 [0.0311431

 80%|████████  | 205/256 [00:12<00:03, 16.37it/s]

tf.Tensor([1 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.         0.00687408 0.         ... 0.         0.         0.        ]
 [0.         0.00144958 0.         ... 0.         0.         0.        ]
 [0.00525665 0.00155735 0.         ... 0.         0.         0.        ]
 ...
 [0.10089111 0.09857178 0.07965088 ... 0.         0.         0.        ]
 [0.06323242 0.08166504 0.04086304 ... 0.         0.         0.        ]
 [0.06384277 0.03268433 0.0024147  ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.09686279 0.04067993 0.         ... 0.         0.         0.        ]
 [0.04077148 0.03323364 0.         ... 0.         0.         0.        ]
 [0.02775574 0.04498291 0.         ... 0.         0.         0.        ]
 ...
 [0.0892334  0.12634277 0.         ... 0.         0.         0.        ]
 [0.10083008 0.20092773 0.1171875  ... 0.         0.         0.        ]
 [0.0878906

 82%|████████▏ | 209/256 [00:12<00:02, 16.98it/s]

tf.Tensor([0 1 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.1352539  0.14648438 0.20056152 ... 0.         0.         0.        ]
 [0.16503906 0.16455078 0.2166748  ... 0.         0.         0.        ]
 [0.11535645 0.18469238 0.2849121  ... 0.         0.         0.        ]
 ...
 [0.07196045 0.05661011 0.         ... 0.         0.9838867  0.        ]
 [0.02215576 0.0531311  0.         ... 0.         0.         0.        ]
 [0.01933289 0.04278564 0.         ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([1 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.02630615 0.03317261 0.03186035 ... 0.         0.         0.        ]
 [0.03152466 0.03662109 0.02719116 ... 0.         0.         0.        ]
 [0.02877808 0.02146912 0.00852966 ... 0.         0.         0.09619141]
 ...
 [0.12561035 0.07568359 0.00402451 ... 0.         0.         0.        ]
 [0.05511475 0.09088135 0.         ... 0.         0.         0.        ]
 [0.0737915

 83%|████████▎ | 213/256 [00:12<00:02, 16.94it/s]

tf.Tensor([0 0 1 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.04983521 0.0322876  0.10754395 ... 0.         0.         0.        ]
 [0.1505127  0.22265625 0.8286133  ... 0.         0.         0.        ]
 [0.11248779 0.19213867 0.62597656 ... 0.0715332  0.         0.        ]
 ...
 [0.11450195 0.20239258 0.02172852 ... 0.         0.         0.        ]
 [0.07598877 0.0836792  0.         ... 0.         0.         0.        ]
 [0.0249176  0.00102043 0.01899719 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([1 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.06665039 0.08349609 0.04345703 ... 0.         0.         0.        ]
 [0.10339355 0.13903809 0.21850586 ... 0.         0.         0.        ]
 [0.1003418  0.13256836 0.13293457 ... 0.         0.         0.        ]
 ...
 [0.11645508 0.2286377  0.28271484 ... 0.         0.         0.        ]
 [0.1114502  0.12915039 0.34960938 ... 0.         0.         0.        ]
 [0.1417236

 85%|████████▍ | 217/256 [00:13<00:02, 16.70it/s]

tf.Tensor([0 0 1 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[3.72924805e-02 1.94091797e-02 0.00000000e+00 ... 3.72123718e-03
  0.00000000e+00 0.00000000e+00]
 [1.37805939e-03 0.00000000e+00 4.82797623e-04 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [6.14929199e-02 3.79638672e-02 2.05993652e-02 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [5.98144531e-02 1.18591309e-01 2.44506836e-01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [5.36499023e-02 1.07421875e-01 7.85522461e-02 ... 0.00000000e+00
  1.12792969e-01 0.00000000e+00]
 [3.11279297e-01 5.04882812e-01 7.27539062e-01 ... 0.00000000e+00
  0.00000000e+00 7.86132812e-02]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 1 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.06787109 0.05639648 0.1673584  ... 0.         0.         0.        ]
 [0.06280518 0.10357666 0.12841797 ... 0.         0.         0.        ]
 [0.0645752  0.09417725 0.2919922  ... 0.         0.         0.        ]
 ...
 

 86%|████████▋ | 221/256 [00:13<00:02, 16.66it/s]

tf.Tensor([0 1 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.00968933 0.01342773 0.         ... 0.         0.         0.        ]
 [0.         0.00634766 0.         ... 0.         0.         0.        ]
 [0.         0.00165844 0.         ... 0.         0.         0.        ]
 ...
 [0.08422852 0.06561279 0.09399414 ... 0.         0.45825195 0.24157715]
 [0.05331421 0.01950073 0.07373047 ... 0.         0.         0.        ]
 [0.04394531 0.03936768 0.         ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 1 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.14587402 0.08111572 0.16113281 ... 0.         0.2541504  0.        ]
 [0.10864258 0.11090088 0.09802246 ... 0.         0.46484375 0.        ]
 [0.10125732 0.10552979 0.19689941 ... 0.         0.         0.        ]
 ...
 [0.03186035 0.01870728 0.         ... 0.         0.         0.        ]
 [0.03652954 0.07794189 0.04379272 ... 0.         0.         0.        ]
 [0.0429382

 88%|████████▊ | 225/256 [00:13<00:01, 16.90it/s]

tf.Tensor([0 0 0 ... 0 0 1], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.07366943 0.10107422 0.1036377  ... 0.         0.         0.14233398]
 [0.10327148 0.07446289 0.10430908 ... 0.         0.         0.        ]
 [0.05328369 0.0199585  0.01158905 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 1 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.02688599 0.08361816 0.05505371 ... 0.         0.         0.        ]
 [0.06335449 0.06292725 0.02687073 ... 0.         0.         0.        ]
 [0.08203125 0.0184021  0.08062744 ... 0.         0.         0.        ]
 ...
 [0.02455139 0.01450348 0.04006958 ... 0.         0.         0.        ]
 [0.02716064 0.02331543 0.         ... 0.         0.         0.        ]
 [0.0003695

 89%|████████▉ | 229/256 [00:13<00:01, 16.53it/s]

tf.Tensor([0 1 0 ... 0 1 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.00644684 0.00419235 0.         ... 0.         0.06234741 0.        ]
 [0.09729004 0.05252075 0.00643921 ... 0.         0.         0.        ]
 [0.11816406 0.03585815 0.02381897 ... 0.         0.         0.        ]
 ...
 [0.0871582  0.08404541 0.00193119 ... 0.         0.         0.        ]
 [0.04718018 0.13012695 0.05407715 ... 0.         0.         0.        ]
 [0.08435059 0.09552002 0.08886719 ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 1 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.01415253 0.00736237 0.05599976 ... 0.         0.         0.        ]
 [0.0635376  0.03277588 0.0574646  ... 0.         0.         0.        ]
 [0.07305908 0.09863281 0.02703857 ... 0.         0.         0.        ]
 ...
 [0.03149414 0.01879883 0.         ... 0.         0.         0.        ]
 [0.06118774 0.04052734 0.         ... 0.         0.         0.13415527]
 [0.0539550

 91%|█████████ | 233/256 [00:14<00:01, 17.19it/s]

tf.Tensor([1 0 0 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.0198822  0.0058136  0.07501221 ... 0.         0.         0.        ]
 [0.07073975 0.05334473 0.08239746 ... 0.         0.         0.        ]
 [0.04174805 0.04296875 0.02268982 ... 0.         0.         0.        ]
 ...
 [0.10803223 0.08044434 0.04553223 ... 0.         0.9838867  0.        ]
 [0.09527588 0.03405762 0.17248535 ... 0.7470703  0.984375   0.        ]
 [0.10955811 0.09741211 0.08563232 ... 0.2364502  0.8496094  0.        ]], shape=(896, 5313), dtype=float32)
tf.Tensor([0 0 1 ... 1 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.09991455 0.06030273 0.02365112 ... 0.         0.         0.        ]
 [0.1217041  0.04138184 0.04086304 ... 0.         0.         0.26513672]
 [0.09783936 0.08081055 0.07177734 ... 0.         0.14221191 0.04666138]
 ...
 [0.03936768 0.04989624 0.05712891 ... 0.         0.         0.        ]
 [0.11383057 0.14086914 0.08306885 ... 0.         0.         0.        ]
 [0.0162811

 92%|█████████▏| 235/256 [00:14<00:01, 16.64it/s]

tf.Tensor([0 0 0 ... 0 0 0], shape=(524288,), dtype=uint8) tf.Tensor(
[[0.04931641 0.05651855 0.00965881 ... 0.         0.         0.        ]
 [0.03424072 0.02105713 0.01287842 ... 0.         0.         0.        ]
 [0.05230713 0.03521729 0.07592773 ... 0.         0.         0.        ]
 ...
 [0.08496094 0.06060791 0.22399902 ... 0.         0.         0.        ]
 [0.01812744 0.02580261 0.06115723 ... 0.         0.         0.        ]
 [0.02302551 0.00608063 0.         ... 0.         0.         0.        ]], shape=(896, 5313), dtype=float32)


 92%|█████████▏| 235/256 [00:14<00:01, 15.88it/s]


KeyboardInterrupt: 

In [51]:
for (sequence1,targets1), (sequence2,targets2) in tqdm(zip(parsed_dataset,new_parsed_dataset),total=256):
    if not tf.reduce_all((tf.equal(sequence1,sequence2))):
        print('Sequences are not identical')
#     else:
#         print('Sequences are identical')
    if not tf.reduce_all(tf.equal(targets1,targets2)):
        print('Targets are not identical')
#     else:
#         print('Targets are identical')

  0%|          | 0/256 [00:00<?, ?it/s]


InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 8960 values, but the requested shape has 4760448
	 [[{{node Reshape}}]] [Op:IteratorGetNext]